apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-fpo0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-fpo0
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-fpo0
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-fpo0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-fpo0
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-goan-tenant/rhtap-demo-app/hacbs-test-project-fpo0@sha256:c026314b5e2a1c8f73c8b4f03e70a489ebd5a4b93b181d35026680eeb3a57d68
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
