apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-fpo0
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-goan-tenant/rhtap-demo-app/hacbs-test-project-fpo0@sha256:def4fdfaf2713a9ab25f4a5956c8e820fb89a271edc03f6deca0ca535a661ab9
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
