apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-fpo0
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-goan-tenant/rhtap-demo-app/hacbs-test-project-fpo0@sha256:52acf7ec48b14f6a40a397047730cc2c7f9d231f8fd80a0ec39e9cf799e0bba3
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
